// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEP_Restaurant_management.Models;

#nullable disable

namespace SEP_Restaurant_management.Migrations
{
    [DbContext(typeof(SepDatabaseContext))]
    partial class SepDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrderDiscount", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("OrderDiscount", (string)null);
                });

            modelBuilder.Entity("OrderTable", b =>
                {
                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("TableId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTable", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A0BCC4099F6");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.CustomDish", b =>
                {
                    b.Property<int>("CustomDishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomDishId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CustomDishId")
                        .HasName("PK__CustomDi__0983331F2E548FBB");

                    b.HasIndex("OrderId");

                    b.ToTable("CustomDishes");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.CustomDishIngredient", b =>
                {
                    b.Property<int>("CustomDishIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomDishIngredientId"));

                    b.Property<int>("CustomDishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CustomDishIngredientId")
                        .HasName("PK__CustomDi__766C71F4DB64C062");

                    b.HasIndex("CustomDishId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CustomDishIngredient", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("DiscountId")
                        .HasName("PK__Discount__E43F6D968FA501D9");

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("DishId")
                        .HasName("PK__Dishes__18834F509F4100E2");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Dishes_CategoryId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.DishIngredient", b =>
                {
                    b.Property<int>("DishIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishIngredientId"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DishIngredientId")
                        .HasName("PK__DishIngr__DBEF30235550CBB8");

                    b.HasIndex(new[] { "DishId" }, "IX_DishIngredient_DishId");

                    b.HasIndex(new[] { "IngredientId" }, "IX_DishIngredient_IngredientId");

                    b.ToTable("DishIngredient", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.DishSize", b =>
                {
                    b.Property<int>("DishSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishSizeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<string>("DishSizeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("DishSizeId")
                        .HasName("PK__DishSize__08A9777A3F3B4F9B");

                    b.HasIndex(new[] { "DishId" }, "IX_DishSize_DishId");

                    b.HasIndex(new[] { "PriceId" }, "IX_DishSize_PriceId");

                    b.ToTable("DishSize", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.ImportBill", b =>
                {
                    b.Property<int>("ImportBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportBillId"));

                    b.Property<int?>("CreateStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("ImportBillId")
                        .HasName("PK__ImportBi__03D1F91021EDD24A");

                    b.HasIndex("CreateStaffId");

                    b.HasIndex(new[] { "SupplierId" }, "IX_ImportBill_SupplierId");

                    b.ToTable("ImportBill", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.ImportBillDetail", b =>
                {
                    b.Property<int>("ImportBillDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportBillDetailId"));

                    b.Property<int>("ImportBillId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("QuantityImport")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("StockQuantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("ImportBillDetailId")
                        .HasName("PK__ImportBi__6BE0A8EEE793E94F");

                    b.HasIndex("IngredientId");

                    b.HasIndex(new[] { "ImportBillId" }, "IX_ImportBillDetail_ImportBillId");

                    b.ToTable("ImportBillDetail", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("CurrentStock")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("IngredientId")
                        .HasName("PK__Ingredie__BEAEB25A7557D19F");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__C3905BCFBEB86ACF");

                    b.HasIndex("ShiftId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Order_CustomerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("DishSizeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D36CE1FF7020");

                    b.HasIndex(new[] { "DishSizeId" }, "IX_OrderDetail_DishSizeId");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderDetail_OrderId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.OrderStaff", b =>
                {
                    b.Property<int>("OrderStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStaffId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("OrderStaffId")
                        .HasName("PK__OrderSta__1E54AA57009598D1");

                    b.HasIndex("OrderId");

                    b.HasIndex("StaffId");

                    b.ToTable("OrderStaff", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PriceValue")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PriceId")
                        .HasName("PK__Price__49575BAFBF1E71D8");

                    b.ToTable("Price", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("ShiftId")
                        .HasName("PK__Shift__C0A838812DF4ED16");

                    b.ToTable("Shift", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StaffCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StaffId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666B4859ACF1F");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TableId")
                        .HasName("PK__Table__7D5F01EE8C9F873C");

                    b.ToTable("Table", (string)null);
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.UserIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEP_Restaurant_management.Models.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderDiscount", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDiscount_Discount");

                    b.HasOne("SEP_Restaurant_management.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDiscount_Order");
                });

            modelBuilder.Entity("OrderTable", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderTable_Order");

                    b.HasOne("SEP_Restaurant_management.Models.Table", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderTable_Table");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.CustomDish", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Order", "Order")
                        .WithMany("CustomDishes")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_CustomDishes_Order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.CustomDishIngredient", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.CustomDish", "CustomDish")
                        .WithMany("CustomDishIngredients")
                        .HasForeignKey("CustomDishId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomDishIngredient_CustomDishes");

                    b.HasOne("SEP_Restaurant_management.Models.Ingredient", "Ingredient")
                        .WithMany("CustomDishIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomDishIngredient_Ingredient");

                    b.Navigation("CustomDish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Customer", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.UserIdentity", "User")
                        .WithOne()
                        .HasForeignKey("SEP_Restaurant_management.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Dish", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Dishes_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.DishIngredient", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .IsRequired()
                        .HasConstraintName("FK_DishIngredient_Dishes");

                    b.HasOne("SEP_Restaurant_management.Models.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_DishIngredient_Ingredient");

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.DishSize", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Dish", "Dish")
                        .WithMany("DishSizes")
                        .HasForeignKey("DishId")
                        .IsRequired()
                        .HasConstraintName("FK_DishSize_Dishes");

                    b.HasOne("SEP_Restaurant_management.Models.Price", "Price")
                        .WithMany("DishSizes")
                        .HasForeignKey("PriceId")
                        .IsRequired()
                        .HasConstraintName("FK_DishSize_Price");

                    b.Navigation("Dish");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.ImportBill", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Staff", "CreateStaff")
                        .WithMany("ImportBills")
                        .HasForeignKey("CreateStaffId")
                        .HasConstraintName("FK_ImportBill_Staff");

                    b.HasOne("SEP_Restaurant_management.Models.Supplier", "Supplier")
                        .WithMany("ImportBills")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_ImportBill_Supplier");

                    b.Navigation("CreateStaff");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.ImportBillDetail", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.ImportBill", "ImportBill")
                        .WithMany("ImportBillDetails")
                        .HasForeignKey("ImportBillId")
                        .IsRequired()
                        .HasConstraintName("FK_ImportBillDetail_ImportBill");

                    b.HasOne("SEP_Restaurant_management.Models.Ingredient", "Ingredient")
                        .WithMany("ImportBillDetails")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_ImportBillDetail_Ingredient");

                    b.Navigation("ImportBill");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Order", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Customer");

                    b.HasOne("SEP_Restaurant_management.Models.Shift", "Shift")
                        .WithMany("Orders")
                        .HasForeignKey("ShiftId")
                        .HasConstraintName("FK_Order_Shift");

                    b.Navigation("Customer");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.OrderDetail", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.DishSize", "DishSize")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DishSizeId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetail_DishSize");

                    b.HasOne("SEP_Restaurant_management.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetail_Order");

                    b.Navigation("DishSize");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.OrderStaff", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.Order", "Order")
                        .WithMany("OrderStaffs")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderStaff_Order");

                    b.HasOne("SEP_Restaurant_management.Models.Staff", "Staff")
                        .WithMany("OrderStaffs")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderStaff_Staff");

                    b.Navigation("Order");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Staff", b =>
                {
                    b.HasOne("SEP_Restaurant_management.Models.UserIdentity", "User")
                        .WithOne()
                        .HasForeignKey("SEP_Restaurant_management.Models.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.CustomDish", b =>
                {
                    b.Navigation("CustomDishIngredients");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Dish", b =>
                {
                    b.Navigation("DishIngredients");

                    b.Navigation("DishSizes");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.DishSize", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.ImportBill", b =>
                {
                    b.Navigation("ImportBillDetails");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Ingredient", b =>
                {
                    b.Navigation("CustomDishIngredients");

                    b.Navigation("DishIngredients");

                    b.Navigation("ImportBillDetails");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Order", b =>
                {
                    b.Navigation("CustomDishes");

                    b.Navigation("OrderDetails");

                    b.Navigation("OrderStaffs");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Price", b =>
                {
                    b.Navigation("DishSizes");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Shift", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Staff", b =>
                {
                    b.Navigation("ImportBills");

                    b.Navigation("OrderStaffs");
                });

            modelBuilder.Entity("SEP_Restaurant_management.Models.Supplier", b =>
                {
                    b.Navigation("ImportBills");
                });
#pragma warning restore 612, 618
        }
    }
}
